sonarqube:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull zaquestion/sonarqube-scanner
    - docker run -v $(pwd):/root/src zaquestion/sonarqube-scanner
